  AddI x1 , x0,   1000  
  AddI x2 , x1,   2000  
  AddI x3 , x2,  -1000  
  AddI x4 , x3,  -2000  
  AddI x5 , x4,   1000  

  SLLI x2 , x1,  4  
  SLLI x3 , x2,  4  
  SLLI x4 , x3,  4  
  SLLI x5 , x4,  4  

  SLLI x2 , x1,  1  
  SLLI x3 , x2,  2  
  SLLI x4 , x3,  3  
  SLLI x5 , x4,  4  

  SLLI x2 , x1, 1 
  SLLI x3 , x2, 1  
  SLLI x4 , x3, 1  
  SLLI x5 , x4, 1

  SLLI x2 , x1, 0 
  SLLI x3 , x2, 0  
  SLLI x4 , x3, 0  
  SLLI x5 , x4, 0
 
  SLLI x2 , x1,  16  
  SLLI x3 , x2,  16  
  SLLI x4 , x3,  16  
  SLLI x5 , x4,  16  

   


  SLLI x2 , x1,  31  
  SLLI x3 , x2,  31  
  SLLI x4 , x3,  31  
  SLLI x5 , x4,  31
  NOP
  NOP
  NOP
  NOP
  NOP

